export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const PRIMARY_ITEM_SELECTED = "PRIMARY_ITEM_SELECTED";
export const SECONDARY_ITEM_SELECTED = "SECONDARY_ITEM_SELECTED";

export const SELECT_BLUEDOG_CASE = "SELECT_BLUEDOG_CASE";
export const UPDATE_BLUEDOG_CASE = "UPDATE_BLUEDOG_CASE";
export const UPDATE_MI3D_CASE_ID = "UPDATE_MI3D_CASE_ID";
export const UPDATE_MI3D_CASE = "UPDATE_MI3D_CASE";

export const SHOW_ERROR_MODAL = "SHOW_ERROR_MODAL";
export const HIDE_ERROR_MODAL = "HIDE_ERROR_MODAL";
